import org.apache.hadoop.ozone.protocolPB.StorageContainerDatanodeProtocolClientSideTranslatorPB;
public class FunctionUse4 {
public void funcUse() {
StorageContainerDatanodeProtocolClientSideTranslatorPB storagecontainerdatanodeprotocolclientsidetranslatorpb = new StorageContainerDatanodeProtocolClientSideTranslatorPB();
storagecontainerdatanodeprotocolclientsidetranslatorpb.lambda$register$2(null,null);
}
}