import org.apache.hadoop.ozone.protocolPB.StorageContainerDatanodeProtocolClientSideTranslatorPB;
public class FunctionUse7 {
public void funcUse() {
StorageContainerDatanodeProtocolClientSideTranslatorPB storagecontainerdatanodeprotocolclientsidetranslatorpb = new StorageContainerDatanodeProtocolClientSideTranslatorPB();
storagecontainerdatanodeprotocolclientsidetranslatorpb.getUnderlyingProxyObject();
}
}